### ISSUE TITLE
The rex image is not loading

### ISSUE THREAD

**Issue by levydlior** [learn-co-curriculum/react-hooks-practice-toy-tales#3]
### Canvas Link

https://learning.flatironschool.com/courses/5193/assignments/186078?module_item_id=413456

### Concern

I think the source for the rex image path is not good

**Comment by lizbur10** [comment]
Hi @levydlior ! Thanks for bringing this to our attention. The url appears to be working now - I'm guessing it was a temporary issue on the source website. I'm going to go ahead and close this issue, but please feel free to reopen it if you're still encountering the problem.

Thanks for contributing to the Flatiron School curriculum 💙
