### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by TheYearIsTwentyGX** [learn-co-curriculum/react-hooks-practice-toy-tales#5]
### Canvas Link

https://learning.flatironschool.com/courses/5634/assignments/194710?module_item_id=437985

### Concern

[Image for Rex](https://static.wikia.nocookie.net/pixar/images/a/a8/Rex_(Toy_Story).png/revision/latest/scale-to-width-down/377?cb=20210221010941) in db.json is now a dead link.

**Comment by lizbur10** [comment]
Hi @TheYearIsTwentyGX ! Looks like it's fine now - I'm guessing it was a temporary connection issue. Let us know if you continue to have trouble and thanks for contributing to the Flatiron School curriculum 💙

**Comment by TheYearIsTwentyGX** [comment]
Hm, it still seems to be pulling up incorrectly for me. I guess dead link wasn't quite the correct term for it. The url does resolve to an image, but not the intended image. Based off the name of the key in db.json, it's supposed to be an image of Rex the dinosaur from Toy Story. However, it seems to be pulling a placeholder picture:

![image](https://user-images.githubusercontent.com/51125873/199496362-931d7520-df95-48af-a86b-2e479d83d7e4.png)

I'm writing this update from my work computer, so it's not a network issue for me. Also, in my experience with the site that is used, that image is their standard placeholder image.
